title: Ted's cave
description: Crawlthroughs and projects
show_downloads: false
google_analytics: 
theme: jekyll-theme-hacker
plugins:
  - jekyll-mathjax-configuration
markdown: kramdown
kramdown:
  math_engine: mathjax


